version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE_KAFKA://localhost:9092,OUTSIDE_KAFKA://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE_KAFKA,OUTSIDE_KAFKA
      KAFKA_LISTENERS: INSIDE_KAFKA://0.0.0.0:9092,OUTSIDE_KAFKA://0.0.0.0:9093
      KAFKA_LISTENER_INTERNAL_PORT: 9092
      KAFKA_LISTENER_EXTERNAL_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE_KAFKA:PLAINTEXT,OUTSIDE_KAFKA:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE_KAFKA
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper
