global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring_app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8081']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka_exporter:9308']