spring:
  application:
    name: Taras-Anichyn-Kafka-test
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/user_orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-orders-group
      auto-offset-reset: earliest
    producer:
      retries: 3


