spring:
  application:
    name: Taras-Anichyn-Kafka-test
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/user_orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-orders-group
      auto-offset-reset: earliest
    producer:
      retries: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # Expose health, info, and metrics endpoints
      base-path: /actuator  # Customize the base path for actuator endpoints
  endpoint:
    health:
      show-details: always  # Show full details for the health endpoint
