server:
  port: 8081

spring:
  application:
    name: Taras-Anichyn-Kafka-test
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://postgres:5432/user_orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-orders-group
      auto-offset-reset: earliest
    producer:
      retries: 3
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always